/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  AddCommentRequest,
  AddDailyResultRequest,
  AddRoundResultRequest,
  Comment,
  DailyResults,
  DeleteCommentRequest,
  GetCommentsResponse,
  GetLeaderboardResponse,
  PersonalTopScoresResponse,
  ResetTestResponse,
  RoundResults,
  SubmitImageRequest,
  UpdatePlayerRequest,
  UpdatePlayerResponse,
} from "../models/index";
import {
  AddCommentRequestFromJSON,
  AddCommentRequestToJSON,
  AddDailyResultRequestFromJSON,
  AddDailyResultRequestToJSON,
  AddRoundResultRequestFromJSON,
  AddRoundResultRequestToJSON,
  CommentFromJSON,
  CommentToJSON,
  DailyResultsFromJSON,
  DailyResultsToJSON,
  DeleteCommentRequestFromJSON,
  DeleteCommentRequestToJSON,
  GetCommentsResponseFromJSON,
  GetCommentsResponseToJSON,
  GetLeaderboardResponseFromJSON,
  GetLeaderboardResponseToJSON,
  PersonalTopScoresResponseFromJSON,
  PersonalTopScoresResponseToJSON,
  ResetTestResponseFromJSON,
  ResetTestResponseToJSON,
  RoundResultsFromJSON,
  RoundResultsToJSON,
  SubmitImageRequestFromJSON,
  SubmitImageRequestToJSON,
  UpdatePlayerRequestFromJSON,
  UpdatePlayerRequestToJSON,
  UpdatePlayerResponseFromJSON,
  UpdatePlayerResponseToJSON,
} from "../models/index";

export interface AddCommentOperationRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
  addCommentRequest: AddCommentRequest;
}

export interface AddDailyResultOperationRequest {
  dailyNo: string;
  groupId: string;
  addDailyResultRequest: AddDailyResultRequest;
}

export interface AddRoundResultOperationRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
  addRoundResultRequest: AddRoundResultRequest;
}

export interface DeleteCommentOperationRequest {
  dailyNo: string;
  roundIndex: string;
  commentId: string;
  groupId: string;
  deleteCommentRequest: DeleteCommentRequest;
}

export interface GetCommentsRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
}

export interface GetDailyResultsRequest {
  dailyNo: string;
  groupId: string;
}

export interface GetLeaderboardRequest {
  groupId: string;
  dailyNo?: string;
}

export interface GetPersonalTopScoresRequest {
  uuid: string;
  groupId: string;
}

export interface GetRoundResultsRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
}

export interface SubmitImageOperationRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
  submitImageRequest: SubmitImageRequest;
}

export interface UpdatePlayerOperationRequest {
  groupId: string;
  updatePlayerRequest: UpdatePlayerRequest;
}

export interface V2GroupGroupIdDailyDailyNoResultOptionsRequest {
  dailyNo: string;
  groupId: string;
}

export interface V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptionsRequest {
  dailyNo: string;
  roundIndex: string;
  commentId: string;
  groupId: string;
}

export interface V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptionsRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
}

export interface V2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptionsRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
}

export interface V2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptionsRequest {
  dailyNo: string;
  roundIndex: string;
  groupId: string;
}

export interface V2GroupGroupIdLeaderboardOptionsRequest {
  groupId: string;
}

export interface V2GroupGroupIdPlayerOptionsRequest {
  groupId: string;
}

export interface V2GroupGroupIdPlayerUuidTopScoresOptionsRequest {
  uuid: string;
  groupId: string;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   */
  async addCommentRaw(
    requestParameters: AddCommentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Comment>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling addComment().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling addComment().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling addComment().',
      );
    }

    if (requestParameters["addCommentRequest"] == null) {
      throw new runtime.RequiredError(
        "addCommentRequest",
        'Required parameter "addCommentRequest" was null or undefined when calling addComment().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/comments`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: AddCommentRequestToJSON(requestParameters["addCommentRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CommentFromJSON(jsonValue),
    );
  }

  /**
   */
  async addComment(
    requestParameters: AddCommentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Comment> {
    const response = await this.addCommentRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async addDailyResultRaw(
    requestParameters: AddDailyResultOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling addDailyResult().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling addDailyResult().',
      );
    }

    if (requestParameters["addDailyResultRequest"] == null) {
      throw new runtime.RequiredError(
        "addDailyResultRequest",
        'Required parameter "addDailyResultRequest" was null or undefined when calling addDailyResult().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: AddDailyResultRequestToJSON(
          requestParameters["addDailyResultRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addDailyResult(
    requestParameters: AddDailyResultOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addDailyResultRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addRoundResultRaw(
    requestParameters: AddRoundResultOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling addRoundResult().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling addRoundResult().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling addRoundResult().',
      );
    }

    if (requestParameters["addRoundResultRequest"] == null) {
      throw new runtime.RequiredError(
        "addRoundResultRequest",
        'Required parameter "addRoundResultRequest" was null or undefined when calling addRoundResult().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: AddRoundResultRequestToJSON(
          requestParameters["addRoundResultRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addRoundResult(
    requestParameters: AddRoundResultOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addRoundResultRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteCommentRaw(
    requestParameters: DeleteCommentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling deleteComment().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling deleteComment().',
      );
    }

    if (requestParameters["commentId"] == null) {
      throw new runtime.RequiredError(
        "commentId",
        'Required parameter "commentId" was null or undefined when calling deleteComment().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling deleteComment().',
      );
    }

    if (requestParameters["deleteCommentRequest"] == null) {
      throw new runtime.RequiredError(
        "deleteCommentRequest",
        'Required parameter "deleteCommentRequest" was null or undefined when calling deleteComment().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/comments/{commentId}`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"commentId"}}`,
            encodeURIComponent(String(requestParameters["commentId"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: DeleteCommentRequestToJSON(
          requestParameters["deleteCommentRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteComment(
    requestParameters: DeleteCommentOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteCommentRaw(requestParameters, initOverrides);
  }

  /**
   */
  async getCommentsRaw(
    requestParameters: GetCommentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetCommentsResponse>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling getComments().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling getComments().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling getComments().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/comments`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCommentsResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getComments(
    requestParameters: GetCommentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetCommentsResponse> {
    const response = await this.getCommentsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getDailyResultsRaw(
    requestParameters: GetDailyResultsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DailyResults>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling getDailyResults().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling getDailyResults().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DailyResultsFromJSON(jsonValue),
    );
  }

  /**
   */
  async getDailyResults(
    requestParameters: GetDailyResultsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DailyResults> {
    const response = await this.getDailyResultsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getLeaderboardRaw(
    requestParameters: GetLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetLeaderboardResponse>> {
    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling getLeaderboard().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["dailyNo"] != null) {
      queryParameters["dailyNo"] = requestParameters["dailyNo"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/leaderboard`.replace(
          `{${"groupId"}}`,
          encodeURIComponent(String(requestParameters["groupId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetLeaderboardResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getLeaderboard(
    requestParameters: GetLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetLeaderboardResponse> {
    const response = await this.getLeaderboardRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getPersonalTopScoresRaw(
    requestParameters: GetPersonalTopScoresRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PersonalTopScoresResponse>> {
    if (requestParameters["uuid"] == null) {
      throw new runtime.RequiredError(
        "uuid",
        'Required parameter "uuid" was null or undefined when calling getPersonalTopScores().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling getPersonalTopScores().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/player/{uuid}/top-scores`
          .replace(
            `{${"uuid"}}`,
            encodeURIComponent(String(requestParameters["uuid"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PersonalTopScoresResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getPersonalTopScores(
    requestParameters: GetPersonalTopScoresRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PersonalTopScoresResponse> {
    const response = await this.getPersonalTopScoresRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getRoundResultsRaw(
    requestParameters: GetRoundResultsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RoundResults>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling getRoundResults().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling getRoundResults().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling getRoundResults().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RoundResultsFromJSON(jsonValue),
    );
  }

  /**
   */
  async getRoundResults(
    requestParameters: GetRoundResultsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RoundResults> {
    const response = await this.getRoundResultsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async resetTestRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ResetTestResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/test/reset`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ResetTestResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async resetTest(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ResetTestResponse> {
    const response = await this.resetTestRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async submitImageRaw(
    requestParameters: SubmitImageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling submitImage().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling submitImage().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling submitImage().',
      );
    }

    if (requestParameters["submitImageRequest"] == null) {
      throw new runtime.RequiredError(
        "submitImageRequest",
        'Required parameter "submitImageRequest" was null or undefined when calling submitImage().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/submit-image`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SubmitImageRequestToJSON(requestParameters["submitImageRequest"]),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async submitImage(
    requestParameters: SubmitImageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.submitImageRaw(requestParameters, initOverrides);
  }

  /**
   */
  async updatePlayerRaw(
    requestParameters: UpdatePlayerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdatePlayerResponse>> {
    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling updatePlayer().',
      );
    }

    if (requestParameters["updatePlayerRequest"] == null) {
      throw new runtime.RequiredError(
        "updatePlayerRequest",
        'Required parameter "updatePlayerRequest" was null or undefined when calling updatePlayer().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-api-key"] =
        await this.configuration.apiKey("x-api-key"); // api_key authentication
    }

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/player`.replace(
          `{${"groupId"}}`,
          encodeURIComponent(String(requestParameters["groupId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: UpdatePlayerRequestToJSON(
          requestParameters["updatePlayerRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdatePlayerResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async updatePlayer(
    requestParameters: UpdatePlayerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdatePlayerResponse> {
    const response = await this.updatePlayerRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoResultOptionsRaw(
    requestParameters: V2GroupGroupIdDailyDailyNoResultOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling v2GroupGroupIdDailyDailyNoResultOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdDailyDailyNoResultOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoResultOptions(
    requestParameters: V2GroupGroupIdDailyDailyNoResultOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdDailyDailyNoResultOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptionsRaw(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptions().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptions().',
      );
    }

    if (requestParameters["commentId"] == null) {
      throw new runtime.RequiredError(
        "commentId",
        'Required parameter "commentId" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/comments/{commentId}`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"commentId"}}`,
            encodeURIComponent(String(requestParameters["commentId"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptions(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsCommentIdOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptionsRaw(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptions().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/comments`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptions(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdDailyDailyNoRoundRoundIndexCommentsOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptionsRaw(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptions().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/result`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptions(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdDailyDailyNoRoundRoundIndexResultOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptionsRaw(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["dailyNo"] == null) {
      throw new runtime.RequiredError(
        "dailyNo",
        'Required parameter "dailyNo" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptions().',
      );
    }

    if (requestParameters["roundIndex"] == null) {
      throw new runtime.RequiredError(
        "roundIndex",
        'Required parameter "roundIndex" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/daily/{dailyNo}/round/{roundIndex}/submit-image`
          .replace(
            `{${"dailyNo"}}`,
            encodeURIComponent(String(requestParameters["dailyNo"])),
          )
          .replace(
            `{${"roundIndex"}}`,
            encodeURIComponent(String(requestParameters["roundIndex"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptions(
    requestParameters: V2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdDailyDailyNoRoundRoundIndexSubmitImageOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdLeaderboardOptionsRaw(
    requestParameters: V2GroupGroupIdLeaderboardOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdLeaderboardOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/leaderboard`.replace(
          `{${"groupId"}}`,
          encodeURIComponent(String(requestParameters["groupId"])),
        ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdLeaderboardOptions(
    requestParameters: V2GroupGroupIdLeaderboardOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdLeaderboardOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async v2GroupGroupIdPlayerOptionsRaw(
    requestParameters: V2GroupGroupIdPlayerOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdPlayerOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/player`.replace(
          `{${"groupId"}}`,
          encodeURIComponent(String(requestParameters["groupId"])),
        ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdPlayerOptions(
    requestParameters: V2GroupGroupIdPlayerOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdPlayerOptionsRaw(requestParameters, initOverrides);
  }

  /**
   */
  async v2GroupGroupIdPlayerUuidTopScoresOptionsRaw(
    requestParameters: V2GroupGroupIdPlayerUuidTopScoresOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["uuid"] == null) {
      throw new runtime.RequiredError(
        "uuid",
        'Required parameter "uuid" was null or undefined when calling v2GroupGroupIdPlayerUuidTopScoresOptions().',
      );
    }

    if (requestParameters["groupId"] == null) {
      throw new runtime.RequiredError(
        "groupId",
        'Required parameter "groupId" was null or undefined when calling v2GroupGroupIdPlayerUuidTopScoresOptions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v2/group/{groupId}/player/{uuid}/top-scores`
          .replace(
            `{${"uuid"}}`,
            encodeURIComponent(String(requestParameters["uuid"])),
          )
          .replace(
            `{${"groupId"}}`,
            encodeURIComponent(String(requestParameters["groupId"])),
          ),
        method: "OPTIONS",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async v2GroupGroupIdPlayerUuidTopScoresOptions(
    requestParameters: V2GroupGroupIdPlayerUuidTopScoresOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.v2GroupGroupIdPlayerUuidTopScoresOptionsRaw(
      requestParameters,
      initOverrides,
    );
  }
}
