// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/api-key.txt"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/enhanced-final-map.js"
    | "/enhanced-map.js"
    | "/icon/32.png"
    | "/leaderboard.js"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
