/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddDailyResultRequest
 */
export interface AddDailyResultRequest {
  /**
   *
   * @type {string}
   * @memberof AddDailyResultRequest
   */
  uuid: string;
  /**
   *
   * @type {number}
   * @memberof AddDailyResultRequest
   */
  totalPoints: number;
}

/**
 * Check if a given object implements the AddDailyResultRequest interface.
 */
export function instanceOfAddDailyResultRequest(
  value: object,
): value is AddDailyResultRequest {
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("totalPoints" in value) || value["totalPoints"] === undefined)
    return false;
  return true;
}

export function AddDailyResultRequestFromJSON(
  json: any,
): AddDailyResultRequest {
  return AddDailyResultRequestFromJSONTyped(json, false);
}

export function AddDailyResultRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddDailyResultRequest {
  if (json == null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    totalPoints: json["totalPoints"],
  };
}

export function AddDailyResultRequestToJSON(json: any): AddDailyResultRequest {
  return AddDailyResultRequestToJSONTyped(json, false);
}

export function AddDailyResultRequestToJSONTyped(
  value?: AddDailyResultRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uuid: value["uuid"],
    totalPoints: value["totalPoints"],
  };
}
