/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoundResult } from "./RoundResult";
import {
  RoundResultFromJSON,
  RoundResultFromJSONTyped,
  RoundResultToJSON,
  RoundResultToJSONTyped,
} from "./RoundResult";
import type { ImageInfo } from "./ImageInfo";
import {
  ImageInfoFromJSON,
  ImageInfoFromJSONTyped,
  ImageInfoToJSON,
  ImageInfoToJSONTyped,
} from "./ImageInfo";

/**
 *
 * @export
 * @interface AddRoundResultRequest
 */
export interface AddRoundResultRequest {
  /**
   *
   * @type {string}
   * @memberof AddRoundResultRequest
   */
  uuid: string;
  /**
   *
   * @type {ImageInfo}
   * @memberof AddRoundResultRequest
   */
  imageInfo: ImageInfo;
  /**
   *
   * @type {RoundResult}
   * @memberof AddRoundResultRequest
   */
  roundResult: RoundResult;
}

/**
 * Check if a given object implements the AddRoundResultRequest interface.
 */
export function instanceOfAddRoundResultRequest(
  value: object,
): value is AddRoundResultRequest {
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("imageInfo" in value) || value["imageInfo"] === undefined) return false;
  if (!("roundResult" in value) || value["roundResult"] === undefined)
    return false;
  return true;
}

export function AddRoundResultRequestFromJSON(
  json: any,
): AddRoundResultRequest {
  return AddRoundResultRequestFromJSONTyped(json, false);
}

export function AddRoundResultRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddRoundResultRequest {
  if (json == null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    imageInfo: ImageInfoFromJSON(json["imageInfo"]),
    roundResult: RoundResultFromJSON(json["roundResult"]),
  };
}

export function AddRoundResultRequestToJSON(json: any): AddRoundResultRequest {
  return AddRoundResultRequestToJSONTyped(json, false);
}

export function AddRoundResultRequestToJSONTyped(
  value?: AddRoundResultRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uuid: value["uuid"],
    imageInfo: ImageInfoToJSON(value["imageInfo"]),
    roundResult: RoundResultToJSON(value["roundResult"]),
  };
}
