/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RoundResults } from "./RoundResults";
import {
  RoundResultsFromJSON,
  RoundResultsFromJSONTyped,
  RoundResultsToJSON,
  RoundResultsToJSONTyped,
} from "./RoundResults";

/**
 *
 * @export
 * @interface DailyResults
 */
export interface DailyResults extends Array<RoundResults> {}

/**
 * Check if a given object implements the DailyResults interface.
 */
export function instanceOfDailyResults(value: object): value is DailyResults {
  return true;
}

export function DailyResultsFromJSON(json: any): DailyResults {
  return DailyResultsFromJSONTyped(json, false);
}

export function DailyResultsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DailyResults {
  return json;
}

export function DailyResultsToJSON(json: any): DailyResults {
  return DailyResultsToJSONTyped(json, false);
}

export function DailyResultsToJSONTyped(
  value?: DailyResults | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
