/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AllTimeLeaderboardEntry } from "./AllTimeLeaderboardEntry";
import {
  AllTimeLeaderboardEntryFromJSON,
  AllTimeLeaderboardEntryFromJSONTyped,
  AllTimeLeaderboardEntryToJSON,
  AllTimeLeaderboardEntryToJSONTyped,
} from "./AllTimeLeaderboardEntry";
import type { LeaderboardEntry } from "./LeaderboardEntry";
import {
  LeaderboardEntryFromJSON,
  LeaderboardEntryFromJSONTyped,
  LeaderboardEntryToJSON,
  LeaderboardEntryToJSONTyped,
} from "./LeaderboardEntry";

/**
 *
 * @export
 * @interface GetLeaderboardResponse
 */
export interface GetLeaderboardResponse {
  /**
   *
   * @type {Array<AllTimeLeaderboardEntry>}
   * @memberof GetLeaderboardResponse
   */
  allTime?: Array<AllTimeLeaderboardEntry>;
  /**
   *
   * @type {Array<LeaderboardEntry>}
   * @memberof GetLeaderboardResponse
   */
  today?: Array<LeaderboardEntry>;
}

/**
 * Check if a given object implements the GetLeaderboardResponse interface.
 */
export function instanceOfGetLeaderboardResponse(
  value: object,
): value is GetLeaderboardResponse {
  return true;
}

export function GetLeaderboardResponseFromJSON(
  json: any,
): GetLeaderboardResponse {
  return GetLeaderboardResponseFromJSONTyped(json, false);
}

export function GetLeaderboardResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetLeaderboardResponse {
  if (json == null) {
    return json;
  }
  return {
    allTime:
      json["allTime"] == null
        ? undefined
        : (json["allTime"] as Array<any>).map(AllTimeLeaderboardEntryFromJSON),
    today:
      json["today"] == null
        ? undefined
        : (json["today"] as Array<any>).map(LeaderboardEntryFromJSON),
  };
}

export function GetLeaderboardResponseToJSON(
  json: any,
): GetLeaderboardResponse {
  return GetLeaderboardResponseToJSONTyped(json, false);
}

export function GetLeaderboardResponseToJSONTyped(
  value?: GetLeaderboardResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    allTime:
      value["allTime"] == null
        ? undefined
        : (value["allTime"] as Array<any>).map(AllTimeLeaderboardEntryToJSON),
    today:
      value["today"] == null
        ? undefined
        : (value["today"] as Array<any>).map(LeaderboardEntryToJSON),
  };
}
