/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
  /**
   *
   * @type {number}
   * @memberof LeaderboardEntry
   */
  score: number;
  /**
   *
   * @type {string}
   * @memberof LeaderboardEntry
   */
  initials: string;
  /**
   *
   * @type {string}
   * @memberof LeaderboardEntry
   */
  uuid: string;
}

/**
 * Check if a given object implements the LeaderboardEntry interface.
 */
export function instanceOfLeaderboardEntry(
  value: object,
): value is LeaderboardEntry {
  if (!("score" in value) || value["score"] === undefined) return false;
  if (!("initials" in value) || value["initials"] === undefined) return false;
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  return true;
}

export function LeaderboardEntryFromJSON(json: any): LeaderboardEntry {
  return LeaderboardEntryFromJSONTyped(json, false);
}

export function LeaderboardEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LeaderboardEntry {
  if (json == null) {
    return json;
  }
  return {
    score: json["score"],
    initials: json["initials"],
    uuid: json["uuid"],
  };
}

export function LeaderboardEntryToJSON(json: any): LeaderboardEntry {
  return LeaderboardEntryToJSONTyped(json, false);
}

export function LeaderboardEntryToJSONTyped(
  value?: LeaderboardEntry | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    score: value["score"],
    initials: value["initials"],
    uuid: value["uuid"],
  };
}
