/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlayerRoundResult
 */
export interface PlayerRoundResult {
  /**
   *
   * @type {string}
   * @memberof PlayerRoundResult
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof PlayerRoundResult
   */
  initials: string;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  roundIndex: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  totalPoints: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  locationPoints: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  timePoints: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  yearsOff: number;
  /**
   *
   * @type {string}
   * @memberof PlayerRoundResult
   */
  distanceOff: string;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  latitude: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  longitude: number;
  /**
   *
   * @type {number}
   * @memberof PlayerRoundResult
   */
  guessedYear: number;
}

/**
 * Check if a given object implements the PlayerRoundResult interface.
 */
export function instanceOfPlayerRoundResult(
  value: object,
): value is PlayerRoundResult {
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("initials" in value) || value["initials"] === undefined) return false;
  if (!("roundIndex" in value) || value["roundIndex"] === undefined)
    return false;
  if (!("totalPoints" in value) || value["totalPoints"] === undefined)
    return false;
  if (!("locationPoints" in value) || value["locationPoints"] === undefined)
    return false;
  if (!("timePoints" in value) || value["timePoints"] === undefined)
    return false;
  if (!("yearsOff" in value) || value["yearsOff"] === undefined) return false;
  if (!("distanceOff" in value) || value["distanceOff"] === undefined)
    return false;
  if (!("latitude" in value) || value["latitude"] === undefined) return false;
  if (!("longitude" in value) || value["longitude"] === undefined) return false;
  if (!("guessedYear" in value) || value["guessedYear"] === undefined)
    return false;
  return true;
}

export function PlayerRoundResultFromJSON(json: any): PlayerRoundResult {
  return PlayerRoundResultFromJSONTyped(json, false);
}

export function PlayerRoundResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlayerRoundResult {
  if (json == null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    initials: json["initials"],
    roundIndex: json["roundIndex"],
    totalPoints: json["totalPoints"],
    locationPoints: json["locationPoints"],
    timePoints: json["timePoints"],
    yearsOff: json["yearsOff"],
    distanceOff: json["distanceOff"],
    latitude: json["latitude"],
    longitude: json["longitude"],
    guessedYear: json["guessedYear"],
  };
}

export function PlayerRoundResultToJSON(json: any): PlayerRoundResult {
  return PlayerRoundResultToJSONTyped(json, false);
}

export function PlayerRoundResultToJSONTyped(
  value?: PlayerRoundResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uuid: value["uuid"],
    initials: value["initials"],
    roundIndex: value["roundIndex"],
    totalPoints: value["totalPoints"],
    locationPoints: value["locationPoints"],
    timePoints: value["timePoints"],
    yearsOff: value["yearsOff"],
    distanceOff: value["distanceOff"],
    latitude: value["latitude"],
    longitude: value["longitude"],
    guessedYear: value["guessedYear"],
  };
}
