/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ResetTestResponse
 */
export interface ResetTestResponse {
  /**
   *
   * @type {string}
   * @memberof ResetTestResponse
   */
  groupId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ResetTestResponse
   */
  playerUuids: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ResetTestResponse
   */
  dailyNos: Array<string>;
}

/**
 * Check if a given object implements the ResetTestResponse interface.
 */
export function instanceOfResetTestResponse(
  value: object,
): value is ResetTestResponse {
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  if (!("playerUuids" in value) || value["playerUuids"] === undefined)
    return false;
  if (!("dailyNos" in value) || value["dailyNos"] === undefined) return false;
  return true;
}

export function ResetTestResponseFromJSON(json: any): ResetTestResponse {
  return ResetTestResponseFromJSONTyped(json, false);
}

export function ResetTestResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResetTestResponse {
  if (json == null) {
    return json;
  }
  return {
    groupId: json["groupId"],
    playerUuids: json["playerUuids"],
    dailyNos: json["dailyNos"],
  };
}

export function ResetTestResponseToJSON(json: any): ResetTestResponse {
  return ResetTestResponseToJSONTyped(json, false);
}

export function ResetTestResponseToJSONTyped(
  value?: ResetTestResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    groupId: value["groupId"],
    playerUuids: value["playerUuids"],
    dailyNos: value["dailyNos"],
  };
}
