/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlayerRoundResult } from "./PlayerRoundResult";
import {
  PlayerRoundResultFromJSON,
  PlayerRoundResultFromJSONTyped,
  PlayerRoundResultToJSON,
  PlayerRoundResultToJSONTyped,
} from "./PlayerRoundResult";

/**
 *
 * @export
 * @interface RoundResults
 */
export interface RoundResults extends Array<PlayerRoundResult> {}

/**
 * Check if a given object implements the RoundResults interface.
 */
export function instanceOfRoundResults(value: object): value is RoundResults {
  return true;
}

export function RoundResultsFromJSON(json: any): RoundResults {
  return RoundResultsFromJSONTyped(json, false);
}

export function RoundResultsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoundResults {
  return json;
}

export function RoundResultsToJSON(json: any): RoundResults {
  return RoundResultsToJSONTyped(json, false);
}

export function RoundResultsToJSONTyped(
  value?: RoundResults | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
