/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdatePlayerRequest
 */
export interface UpdatePlayerRequest {
  /**
   *
   * @type {string}
   * @memberof UpdatePlayerRequest
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePlayerRequest
   */
  initials: string;
}

/**
 * Check if a given object implements the UpdatePlayerRequest interface.
 */
export function instanceOfUpdatePlayerRequest(
  value: object,
): value is UpdatePlayerRequest {
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("initials" in value) || value["initials"] === undefined) return false;
  return true;
}

export function UpdatePlayerRequestFromJSON(json: any): UpdatePlayerRequest {
  return UpdatePlayerRequestFromJSONTyped(json, false);
}

export function UpdatePlayerRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePlayerRequest {
  if (json == null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    initials: json["initials"],
  };
}

export function UpdatePlayerRequestToJSON(json: any): UpdatePlayerRequest {
  return UpdatePlayerRequestToJSONTyped(json, false);
}

export function UpdatePlayerRequestToJSONTyped(
  value?: UpdatePlayerRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uuid: value["uuid"],
    initials: value["initials"],
  };
}
