/* tslint:disable */
/* eslint-disable */
/**
 * tgs_v2
 * Timeguessr Social API V2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdatePlayerResponse
 */
export interface UpdatePlayerResponse {
  /**
   *
   * @type {string}
   * @memberof UpdatePlayerResponse
   */
  groupId: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePlayerResponse
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePlayerResponse
   */
  initials: string;
}

/**
 * Check if a given object implements the UpdatePlayerResponse interface.
 */
export function instanceOfUpdatePlayerResponse(
  value: object,
): value is UpdatePlayerResponse {
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("initials" in value) || value["initials"] === undefined) return false;
  return true;
}

export function UpdatePlayerResponseFromJSON(json: any): UpdatePlayerResponse {
  return UpdatePlayerResponseFromJSONTyped(json, false);
}

export function UpdatePlayerResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePlayerResponse {
  if (json == null) {
    return json;
  }
  return {
    groupId: json["groupId"],
    uuid: json["uuid"],
    initials: json["initials"],
  };
}

export function UpdatePlayerResponseToJSON(json: any): UpdatePlayerResponse {
  return UpdatePlayerResponseToJSONTyped(json, false);
}

export function UpdatePlayerResponseToJSONTyped(
  value?: UpdatePlayerResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    groupId: value["groupId"],
    uuid: value["uuid"],
    initials: value["initials"],
  };
}
